# Generated by Django 4.2.21 on 2025-05-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('src_ip', models.GenericIPAddressField(verbose_name='Источник')),
                ('dst_ip', models.GenericIPAddressField(verbose_name='Назначение')),
                ('protocol', models.CharField(blank=True, max_length=10)),
                ('action', models.CharField(help_text='ALLOW / DROP / etc.', max_length=32)),
                ('raw_message', models.TextField()),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-created_at'],
            },
        ),
    ]
